version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: vehicle-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  nestjs-app:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
